package pojos;
// Generated 25-ene-2024 20:30:11 by Hibernate Tools 4.3.1

/**
 * PaseSala generated by hbm2java
 */
public class PaseSala implements java.io.Serializable {

    private Integer id;
    private Pases pases;
    private Salas salas;

    public PaseSala() {
    }

    public PaseSala(Pases pases, Salas salas) {
        this.pases = pases;
        this.salas = salas;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Pases getPases() {
        return this.pases;
    }

    public void setPases(Pases pases) {
        this.pases = pases;
    }

    public Salas getSalas() {
        return this.salas;
    }

    public void setSalas(Salas salas) {
        this.salas = salas;
    }

}
