package pojos;
// Generated 25-ene-2024 20:30:11 by Hibernate Tools 4.3.1

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

    private Integer uid;
    private String usuario;
    private String pclave;

    public Usuarios() {
    }

    public Usuarios(String usuario, String pclave) {
        this.usuario = usuario;
        this.pclave = pclave;
    }

    public Integer getUid() {
        return this.uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getPclave() {
        return this.pclave;
    }

    public void setPclave(String pclave) {
        this.pclave = pclave;
    }

}
